version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sentinel-db
    environment:
      - POSTGRES_USER=sentinel_user
      - POSTGRES_PASSWORD=sentinel_pass
      - POSTGRES_DB=sentinel_gateway
    ports:
      - "6399:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: sentinel-redis
    ports:
      - "6380:6379"
    restart: always

volumes:
  postgres_data: