services:
  postgres:
    image: postgres:16-alpine
    container_name: sentinel_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sentinel_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sentinel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: